define(function HelpTemplate() {
    var template = [
        '<div class="wrapper clearfix" id="top">',
            '{{#def.header || ""}}',
            '<div class="main">',
                '<a href="#top" class="move-top" title="Move to top">Move to top</a>',
                '<section class="help-container">',
                '<div class="container">',
                  '<section class="clearfix help-header">',
                      '<section class="help-header-title">',
                          '<h2>{{help.header.title}}</h2>',
                      '</section>',
                      '<section class="localization">{{#def.locale || ""}}</section>',
                  '</section>',
                  '<div class="clearfix">',
                    '<div class="left-panel">',
                      '<ul class="menu">',
                        '<li><a href="#quick_start">{{help.left.panel.quick.start}}</a></li>',
                        '<li><a href="#interface">{{help.left.panel.interface}}</a></li>',
                        '{{?it.features.showNavigation === true}}',
                              '<li><a href="#toc">{{help.left.panel.toc}}</a></li>',
                        '{{?}}',
                        '<li><a href="#queries">{{help.left.panel.queries}}</a></li>',
                        '<li><a href="#floating_contexual_menu">{{help.left.panel.float.contexual.menu}}</a></li>',
                        '<li><a href="#insert">{{help.left.panel.insert}}</a></li>',
                        '<li><a href="#instruct">{{help.left.panel.instruct}}</a></li>',
                        '<li><a href="#general_attachment">{{help.left.panel.general.attachment}}</a></li>',
                        '<li><a href="#graphic_pdf">{{help.left.panel.graphic.pdf}}</a></li>',
                        '<li><a href="#math_editing">{{help.left.panel.math.editing}}</a></li>',
                        '<li><a href="#edit_log">{{help.left.panel.edit.log}}</a></li>',
                        '<li><a href="#save_n_submit">{{help.left.panel.save.submit}}</a></li>',
                        '<li><a href="#annotate_pdf">{{help.left.panel.annotate.pdf}}</a></li>',
                      '</ul>',
                    '</div>',
                    '<div class="right-panel">',
                      '<div class="help-container" id="quick_start">',
                        '<h3>{{help.left.panel.quick.start}}</h3>',
                        '<div class="help-content">',
                          '<p>{{help.right.panel.quick.option.text}}</p>',
                          '<ol>',
                            '<li>{{help.right.panel.quick.option.one}}</li>',
                            '<li>{{help.left.panel.annotate.pdf}}{{help.right.panel.quick.option.two}}</li>',
                          '</ol>',
                          '<p>{{help.right.panel.quick.start.heading}}</p>',
                          '<ul>',
                            '<li>{{help.right.panel.check.surname}}</li>',
                            '<li>{{help.right.panel.check.copyeditor.changes}}</li>',
                            '<li>{{help.right.panel.answer.queries}}</li>',
                            '<li>{{help.right.panel.annotate.graphics}}</li>',
                            '{{?it.features.showPaginateProof === true}}',
                            '{{?}}',
                          '</ul>',
                        '</div>',
                      '</div>',
                      '<div class="help-container" id="interface">',
                        '<h3>{{help.left.panel.interface}}</h3>',
                        '<div class="help-content">',
                          '<ul>',
                            '<li>{{help.right.panel.interface.help.content.point1}} <img src="/images/help/proceed_button.png" alt="[Image: Proceed]" title="Proceed"> {{help.right.panel.interface.help.content.point2}}</li>',
                            "<li>{{help.right.panel.quick.interface.pdf.text}}</li>",
                            '{{?it.features.showPaginateProof === false}}',
                              '{{?it.features.showNavigation === true}}',
                                '<li class="bullet-free resize-img"><img src="/images/help/interface-with-toc.png" alt="[Image: Interface]" title="Interface"></li>',
                              '{{??it.features.showNavigation === false}}',
                                '<li class="bullet-free resize-img"><img src="/images/help/interface-without-toc.png" alt="[Image: Interface]" title="Interface"></li>',
							  '{{?}}',
                            '{{?}}{{?it.features.showPaginateProof === true}}',
							  '{{?it.features.showNavigation === true}}',
                                '<li class="bullet-free resize-img"><img src="/images/help/interface-with-toc.png" alt="[Image: Interface]" title="Interface"></li>',
                              '{{??it.features.showNavigation === false}}',
                                '<li class="bullet-free resize-img"><img src="/images/help/interface-without-toc.png" alt="[Image: Interface]" title="Interface"></li>',
							  '{{?}}',
                            '{{?}}',
                          '</ul>',
                          '<h4>{{help.right.panel.interface.left.pane}}</h4>',
                          '<ul>',
                            '<li>{{help.right.panel.interface.left.pane.para.pane.house}}</li>',
                            '<li>{{help.right.panel.interface.left.pane.para.supplementary}}</li>',
                          '</ul>',
                          '<h4>{{help.right.panel.interface.right.pane}}</h4>',
                          '{{?it.features.showNavigation === true}}',
                            '<ul>',
                              '<li>{{help.right.panel.interface.right.pane.para.4.controls.quicklinkon}}</li>',
                            '</ul>',
                          '{{??it.features.showNavigation === false}}',
                            '<ul>',
                              '<li>{{help.right.panel.interface.right.pane.para.4.controls.quicklinkoff}}</li>',
                            '</ul>',
                          '{{?}}',
                          '{{?it.features.showPaginateProof === true}}',
                          '{{?}}',
                        '</div>',
                      '</div>',
                      '{{?it.features.showNavigation === true}}',
                        '<div class="help-container" id="toc">',
                          '<h3>{{help.left.panel.toc}}</h3>',
                          '<div class="help-content">',
                            '<ul>',
                              '<li >{{help.right.panel.toc.help.content.overview}}</li>',
                              '<li >{{help.right.panel.toc.help.content.initial.view}}</li>',
                              '<li class="bullet-free" ><img src="/images/help/quicklink_1.png" alt="[Image: {{help.right.panel.toc.help.image.ellipsis.panel}}]" title="{{help.right.panel.toc.help.image.ellipsis.panel}}">',
                              '<li>{{help.right.panel.toc.help.content.controls.expand}}</li>',
                              '<li class="bullet-free"><img src="/images/help/quicklink_2.png" alt="[Image: {{help.right.panel.toc.help.image.multilevel.panel}}]" title="{{help.right.panel.toc.help.image.multilevel.panel}}">',
                              '<li >{{help.right.panel.toc.help.content.point1}}</li>',
                              '<li >{{help.right.panel.toc.help.content.point2}}</li>',
                              '<li >{{help.right.panel.toc.help.content.point3}}</li>',
                              '<li >{{help.right.panel.toc.help.content.point4}}</li>',
                            '</ul>',
                            '<h4>{{help.right.panel.toc.help.image.keyboard.shortcut.title}}</h4>',
                            '<ul>',
                              '<li class="bullet-free">',
                                '<img src="/images/help/keyboard_shortcut.png" alt="[Image: {{help.right.panel.toc.help.image.keyboard.shortcut}}]" title="{{help.right.panel.toc.help.image.keyboard.shortcut}}">',
                              '</li>',
                            '</ul>',
                            '<ul>',
                              '<li>{{help.right.panel.toc.help.content.figure.and.table.overview}}</li>',
                              '<li class="bullet-free"><img src="/images/help/quicklink_3.png" alt="[Image: {{help.right.panel.toc.help.image.figure.and.table.overview}}]" title="{{help.right.panel.toc.help.image.figure.and.table.overview}}">',
                              '<li>{{help.right.panel.toc.help.content.figure.and.table.navigate}}</li>',
                              '<li class="bullet-free resize-img"><img src="/images/help/quicklink_4.png" alt="[Image: {{help.right.panel.toc.help.image.figure.and.table.navigate}}]" title="{{help.right.panel.toc.help.image.figure.and.table.navigate}}">',
                            '</ul>',
                          '</div>',
                        '</div>',
                      '{{?}}',
                      '<div class="help-container" id="queries">',
                        '<h3>{{help.left.panel.queries}}</h3>',
                        '<div class="help-content">',
                          '<ul>',
                            '<li class="bullet-free resize-img"><img src="/images/help/queries.png" alt="[Image: Queries]" title="Queries"></li>',
                            '<li>{{help.right.panel.queries.para.dialog}}</li>',
                            '<li class="bullet-free"><img src="/images/help/special_characters_pane.png" alt="[Image: Special Characters]" title="Special Characters"></li>',
                            '<li>{{help.right.panel.queries.para.special.char}}</li>',
                            '<li>{{help.right.panel.queries.para.special.char2}}</li>',
                            '<li id="respond_query">{{help.right.panel.queries.para.attachment}}',
                              '<p>* <span class="note">{{help.right.panel.queries.para.attachment.note}}</span></p>',
                            '</li>',
                            '<li class="bullet-free"><img src="/images/help/query_response.png" alt="[Image: Response]" title="Response"></li>',
                            '<li>{{help.right.panel.queries.para.save.1}} {{help.right.panel.queries.para.save.2}}</li>',
                          '</ul>',
                        '</div>',
                      '</div>',
                      '<div class="help-container" id="floating_contexual_menu">',
                        '<h3>{{help.left.panel.float.contexual.menu}}</h3>',
                        '<div class="help-content">',
                          '<ul>',
                            '<li>{{help.right.panel.floating.menu.formatting}}</li>',
                            '<li>{{help.right.panel.floating.menu.editing.controls}}</li>',
                            '<li class="bullet-free"><img src="/images/help/floating_click_menu.png" alt="[Image: Contexual Menu]" title="Contexual Menu"></li>',
                            '<li>{{help.right.panel.floating.menu.selecting.controls}}</li>',
                            '<li class="bullet-free"><img src="/images/help/formatting_control.png" alt="[Image: Contexual Menu]" title="Contexual Menu"></li>',
                          '</ul>',
                        '</div>',
                      '</div>',
                      '<div class="help-container" id="insert">',
                        '<h3>{{help.left.panel.insert}}</h3>',
                        '<div class="help-content">',
                          '<ul>',
                            '<li class="bullet-free"><img src="/images/help/insert_menu.png" alt="[Image: Insert]" title="Insert"></li>',
                            '<li>{{help.right.panel.insert.controls.cursor.text}}</li>',
                            '<li>{{help.right.panel.insert.controls.before.text}} <img src="/images/help/insert_control.png" alt="[Image: Insert Control]" title="Insert Control"> {{help.right.panel.insert.controls.after.text}} {{help.right.panel.insert.proceed.after.text}}</li>',
                            '<li class="bullet-free"><img src="/images/help/after_insert_text.png" alt="[Image: Insert]" title="Insert"></li>',
                            '<li>{{help.right.panel.insert.save.inserted.text.1}} {{help.right.panel.insert.save.inserted.text.2}}</li>',
                            '<li id="floating_menu">{{help.right.panel.insert.clear.before.text}} {{help.right.panel.insert.clear.after.text}}</li>',
                            '<li class="bullet-free"><img src="/images/help/clear_insert_text.png" alt="[Image: Clear Insert]" title="Clear Insert" style="width:85%"></li>',
                            '<li>{{help.right.panel.insert.undo.clear.before.text}}<img src="/images/help/undo.png" alt="[Image: Undo Control]" title="Undo Control"> {{help.right.panel.insert.undo.clear.after.text}}</li>',
                            '{{?it.features.showPaginateProof === true}}',
                            '{{?}}',
                          '</ul>',
                        '</div>',
                      '</div>',
                      '<div class="help-container" id="instruct">',
                        '<h3>{{help.left.panel.instruct}}</h3>',
                        '<div class="help-content">',
                          '<ul>',
                            '<li>{{help.right.panel.instruct.pass.publisher}}</li>',
                            '<li class="bullet-free"><img src="/images/help/instruct_menu.png" alt="[Image: Instruct Menu]" title="Instruct Menu"></li>',
                            '<li>{{help.right.panel.instruct.controls.before.text}} <img src="/images/help/instruct_control.png" alt="[Image: Instruct Control]" title="Instruct Control"> {{help.right.panel.instruct.controls.after.text}} {{help.right.panel.instruct.proceed.after.text}} (<a href="#respond_query">{{help.right.panel.interface.left.pane.para.see.details}}</a>).</li>',
                            '<li class="bullet-free"><img src="/images/help/instruct_pane.png" alt="[Image: Instruct Panel]" title="Instruct Panel"></li>',
                          '</ul>',
                        '</div>',
                      '</div>',
                      '<div class="help-container" id="general_attachment">',
                        '<h3>{{help.left.panel.general.attachment}}</h3>',
                        '<div class="help-content resize-img">',
                          '<ul>',
                            '<li class="bullet-free"><img src="/images/help/generic_attachment.png" alt="[Image: generic attachment]" title="generic attachment" style="width:70%;"></li>',
                            '<li>{{help.right.panel.general.attachment.option}} <a href="#respond_query">{{help.right.panel.general.attachment.hyperlink}}</a> {{help.right.panel.general.attachment.option1}}</li>',
                          '</ul>',
                        '</div>',
                      '</div>',
                      '<div class="graphic-container" id="graphic_pdf">',
                        '<h3>{{help.left.panel.graphic.pdf}}</h3>',
                        '<div class="help-content">',
                          '<ul>',
                            '<li>{{help.right.panel.graphic.pdf.text.one}}</li>',
                            '<li style="font-weight:bold">{{help.right.panel.graphic.pdf.text.two}}</li>',
                            '<li>{{help.right.panel.graphic.pdf.text.three}}</li>',
                            '<li class="bullet-free"><img src="/images/help/graphic_pdf.png" alt="[Image: graphic_pdf]" title="graphic_pdf"></li>',
                            '<li>{{help.right.panel.graphic.pdf.text.four}}</li>',
                            '<li>{{help.right.panel.graphic.pdf.text.five}}</li>',
                            '<li>{{help.right.panel.graphic.pdf.text.six}}</li>',
                          '</ul>',
                        '</div>',
                      '</div>',
                      '<div class="help-container" id="math_editing">',
                        '<h3>{{help.left.panel.math.editing}}</h3>',
                        '<div class="help-content resize-img">',
                          '<ul>',
                            '<li>{{help.right.panel.math.editing.option.one}}</li>',
                            '<li>{{help.right.panel.math.editing.option.two}}</li>',
                            '<li class="bullet-free inline-block"><img src="/images/help/math_annotation_one.png" alt="[Image: Edit Equation]" title="Edit Equation" style="width:70%";></li>',
                            '<li class="bullet-free inline-block"><img src="/images/help/math_annotation_two.png" alt="[Image: Edit Equation]" title="Edit Equation" style="width:70%";></li>',
                            '<li>{{help.right.panel.math.editing.option.three}}</li>',
                            '<li class="bullet-free"><img src="/images/help/math_annotation.png" alt="[Image: Math Annotation]" title="Math Annotation" style="width:70%";></li>',
                          '</ul>',
                        '</div>',
                      '</div>',
                      '<div class="help-container" id="edit_log">',
                        '<h3>{{help.left.panel.edit.log}}</h3>',
                        '<div class="help-content">',
                          '<ul>',
                            '<li>{{help.right.panel.edit.log.edit.list}}</li>',
                            '<li class="bullet-free"><img src="/images/help/rsc_edit_list.png" alt="[Image: Edit Log]" title="Edit Log"></li>',
                            '<li>{{help.right.panel.edit.log.edit.location}}</li>',
                            '<li class="bullet-free"><img src="/images/help/rsc_edit_flash.png" alt="[Image: Edit]" title="Edit"></li>',
                            '<li>{{help.right.panel.edit.log.floating.menu}}</li>',
                          '</ul>',
                        '</div>',
                      '</div>',
                      '<div class="help-container" id="save_n_submit">',
                        '<h3>{{help.left.panel.save.submit}}</h3>',
                        '<div class="help-content">',
                          '<ul>',
                            '<li>{{help.right.panel.save.submit.save.button.before.text}} <img src="/images/help/save_button.png" alt="[Image: Save]" title="Save"> {{help.right.panel.save.submit.save.button.after.text}}</li>',
                          '</ul>',
                          '<ul>',
                            '<li>{{help.right.panel.save.submit.session.report.before.text}} <img src="/images/help/download_edit.png" alt="[Image: Session Report]" title="Session Report"> {{help.right.panel.save.submit.session.report.after.text}}</li>',
                          '</ul>',
                          '<ul>',
                            '<li>{{help.right.panel.save.submit.submit.button.before.text}}<img src="/images/help/submit_button.png" alt="[Image: Submit]" title="Submit">{{help.right.panel.save.submit.submit.button.after.text}}</li>',
                          '</ul>',
                        '</div>',
                      '</div>',
                      '<div class="annotatepdf-container" id="annotate_pdf">',
                        '<h3>{{help.left.panel.annotate.pdf}}</h3>',
                        '<div class="help-content">',
                          '<ul>',
                            '<li>{{help.right.panel.annotate.pdf.text.one}}</li>',
                            '<li>{{help.right.panel.annotate.pdf.text.two}}</li>',
                            '<li class="bullet-free"><img src="/images/help/annotate_pdf.png" alt="[Image: annotate_pdf]" title="annotate_pdf"></li>',
                            '<li>{{help.right.panel.annotate.pdf.text.three}}</li>',
                            '<li style="font-weight:bold">{{help.right.panel.annotate.pdf.text.important}}</li>',
                          '</ul>',
                        '</div>',
                      '</div>',
                    '</div>',
                  '</div>',
                '</div>',
                '</section>',
            '</div>',
        '</div>'
    ];

    return template.join('');
});
