define(function OfflineProofCorrectorTemplate() {
    var template = [
            '<article class="content-list">',
                '<h2>{{offline.page.heading}}</h2>',
                '<p class="steps-annotate-title">{{offline.page.steps.heading}}</p>',
                '<ol class="off-line-content-list">',
                    '<li>',
                        '<p>1. {{offline.page.download.pdf}}</p>',
                        '<section class="download-list">',
                            '<ul>',
                                '<li class="head"><h3>{{offline.page.download.files}}</h3></li>',
                                '<li class="title">',
                                    '<span>{{offline.page.filename}}</span>',
                                    '<span class="size">{{offline.page.size}} (KB)</span>',
                                '</li>',
                                '{{~it.proofingFiles :file:index}}',
                                    '<li>',
                                        '<span title="{{=file.name}}">{{=file.name}}</span>',
                                        '<span>{{=file.size}}</span>',
                                        '<a target="_blank" href="{{=file.url}}" class="file-download">{{offline.page.download}}</a>',
                                    '</li>',
                                '{{~}}',
                            '</ul>',
                        '</section>',
                    '</li>',
                    '<li>',
                        '<p>2. {{offline.proofcorrector.annoatate.pdf}}',
                            '{{offline.page.annoatate.pdf.instruction}} <a target="_blank" href="http://get.adobe.com/reader/">{{offline.page.click.here}}</a>',
                        '</p>',
                        '<section class="upload-corrections">',
                            '<h3>{{offline.page.upload.correction}}</h3>',
                            '{{?it.readOnly == false}}',
                                '<p class="clearfix">',
                                    '<input type="file" name="file" class="attach-file">',
                                    '<span class="limit">* {{offline.page.upload.limit}}</span>',
                                '</p>',
                            '{{?}}',
                            '<ul class="uploaded-file-list">',
                            '</ul>',
                        '</section>',
                    '</li>',
                    '<li><p>3. {{offline.page.proofcorrector.upload.annotate}}</p></li>',
                '</ol>',
            '</article>'
        ];

    return template.join('');
});
