define(function ProofCorrectorTemplate() {
    var template = [
            '<article class="content-list">',
                '<h2>{{landing.page.welcome}} {{!it.actorName}},</h2>',
                '<p class="info">{{landing.page.below.welcome.instruction.corrector}}</p>',
                '<h2 class="submit-title">{{landing.page.do.step.before.submit}}</h2>',
                '<section class="welcome-content">',
                    '<ul class="screen-list">',
                        '<li>',
                            '<section class="img-list">',
                                '<img src="/images/landing/img_pc_new_1.png" width="65" height="60" alt="">',
                            '</section>',
                            '<p>',
                                '{{landing.page.instruction.author.name}}',
                            '</p>',
                        '</li>',
                        '<li>',
                            '<section class="img-list">',
                                '<img src="/images/landing/img_pc_rsc_2.jpg" width="65" height="60" alt="">',
                            '</section>',
                        '<p>',
                            '{{landing.page.instruction.edit.log}}',
                        '</p>',
                        '</li>',
                        '<li>',
                            '<section class="img-list">',
                                '<img src="/images/landing/img_pc_3.png" width="65" height="60" alt="">',
                            '</section>',
                            '<p>',
                                '{{landing.page.instruction.queries}}',
                            '</p>',
                        '</li>',
                        '<li>',
                            '<section class="img-list">',
                                '<img src="/images/landing/img_pc_rsc_5.png" width="65" height="60" alt="">',
                            '</section>',
                            '<p>',
                                '{{landing.page.instruction.graphics}}',
                            '</p>',
                        '</li>',
                        '<li>',
                            '<section class="img-list">',
                                '<img src="/images/landing/img_pc_6.jpg" width="65" height="60" alt="">',
                            '</section>',
                            '<p>',
                                '{{landing.page.instruction.view.page.proof}}',
                            '</p>',
                        '</li>',
                    '</ul>',
                '</section>',
            '</article>'
        ];

    return template.join('');
});
