define([], function() {
    return [
        ['33', '!'],
        ['34', '&quot;'],
        ['35', '#'],
        ['36', '$'],
        ['37', '%'],
        ['38', '&amp;'],
        ['39', '\''],
        ['40', '('],
        ['41', ')'],
        ['42', '*'],
        ['43', '+'],
        ['45', '-'],
        ['46', '.'],
        ['47', '/'],
        ['48', '0'],
        ['49', '1'],
        ['50', '2'],
        ['51', '3'],
        ['52', '4'],
        ['53', '5'],
        ['54', '6'],
        ['55', '7'],
        ['56', '8'],
        ['57', '9'],
        ['58', ':'],
        ['59', ';'],
        ['60', '&lt;'],
        ['61', '='],
        ['62', '&gt;'],
        ['63', '?'],
        ['64', '@'],
        ['91', '['],
        ['93', ']'],
        ['94', '^'],
        ['95', '_'],
        ['96', '`'],
        ['123', '{'],
        ['124', '|'],
        ['125', '}'],
        ['126', '~'],
        ['8364', 'EURO SIGN'],
        ['8216', 'LEFT SINGLE QUOTATION MARK'],
        ['8217', 'RIGHT SINGLE QUOTATION MARK'],
        ['8220', 'LEFT DOUBLE QUOTATION MARK'],
        ['8221', 'RIGHT DOUBLE QUOTATION MARK'],
        ['8211', 'EN DASH'],
        ['8212', 'EM DASH'],
        ['161', 'INVERTED EXCLAMATION MARK'],
        ['162', 'CENT SIGN'],
        ['163', 'POUND SIGN'],
        ['164', 'CURRENCY SIGN'],
        ['165', 'YEN SIGN'],
        ['166', 'BROKEN BAR'],
        ['167', 'SECTION SIGN'],
        ['168', 'DIAERESIS'],
        ['169', 'COPYRIGHT SIGN'],
        ['170', 'FEMININE ORDINAL INDICATOR'],
        ['171', 'LEFT-POINTING DOUBLE ANGLE QUOTATION MARK'],
        ['172', 'NOT SIGN'],
        ['174', 'REGISTERED SIGN'],
        ['175', 'MACRON'],
        ['176', 'DEGREE SIGN'],
        ['178', 'SUPERSCRIPT TWO'],
        ['179', 'SUPERSCRIPT THREE'],
        ['180', 'ACUTE ACCENT'],
        ['181', 'MICRO SIGN'],
        ['182', 'PILCROW SIGN'],
        ['183', 'MIDDLE DOT'],
        ['184', 'CEDILLA'],
        ['185', 'SUPERSCRIPT ONE'],
        ['186', 'MASCULINE ORDINAL INDICATOR'],
        ['187', '&raquo;'],
        ['188', 'VULGAR FRACTION ONE QUARTER'],
        ['189', 'VULGAR FRACTION ONE HALF'],
        ['190', 'VULGAR FRACTION THREE QUARTERS'],
        ['191', 'INVERTED QUESTION MARK'],
        ['192', 'LATIN SMALL LETTER A WITH GRAVE'],
        ['193', 'LATIN SMALL LETTER A WITH ACUTE'],
        ['194', 'LATIN SMALL LETTER A WITH CIRCUMFLEX'],
        ['195', 'LATIN SMALL LETTER A WITH TILDE'],
        ['196', 'LATIN SMALL LETTER A WITH DIAERESIS'],
        ['197', 'LATIN SMALL LETTER A WITH RING ABOVE'],
        ['198', 'LATIN SMALL LETTER AE'],
        ['199', 'LATIN SMALL LETTER C WITH CEDILLA'],
        ['200', 'LATIN SMALL LETTER E WITH GRAVE'],
        ['201', 'LATIN SMALL LETTER E WITH ACUTE'],
        ['202', 'LATIN SMALL LETTER E WITH CIRCUMFLEX'],
        ['203', 'LATIN SMALL LETTER E WITH DIAERESIS'],
        ['204', 'LATIN SMALL LETTER I WITH GRAVE'],
        ['205', 'LATIN SMALL LETTER I WITH ACUTE'],
        ['206', 'LATIN SMALL LETTER I WITH CIRCUMFLEX'],
        ['207', 'LATIN SMALL LETTER I WITH DIAERESIS'],
        ['208', 'LATIN SMALL LETTER ETH'],
        ['209', 'LATIN SMALL LETTER N WITH TILDE'],
        ['210', 'LATIN SMALL LETTER O WITH GRAVE'],
        ['211', 'LATIN SMALL LETTER O WITH ACUTE'],
        ['212', 'LATIN SMALL LETTER O WITH CIRCUMFLEX'],
        ['213', 'LATIN SMALL LETTER O WITH TILDE'],
        ['214', 'LATIN SMALL LETTER O WITH DIAERESIS'],
        ['215', 'MULTIPLICATION SIGN'],
        ['216', 'LATIN SMALL LETTER O WITH STROKE'],
        ['217', 'LATIN SMALL LETTER U WITH GRAVE'],
        ['218', 'LATIN SMALL LETTER U WITH ACUTE'],
        ['219', 'LATIN SMALL LETTER U WITH CIRCUMFLEX'],
        ['220', 'LATIN SMALL LETTER U WITH DIAERESIS'],
        ['221', 'LATIN SMALL LETTER Y WITH ACUTE'],
        ['222', 'LATIN SMALL LETTER THORN'],
        ['223', 'LATIN SMALL LETTER SHARP S'],
        ['224', 'LATIN SMALL LETTER A WITH GRAVE'],
        ['225', 'LATIN SMALL LETTER A WITH ACUTE'],
        ['226', 'LATIN SMALL LETTER A WITH CIRCUMFLEX'],
        ['227', 'LATIN SMALL LETTER A WITH TILDE'],
        ['228', 'LATIN SMALL LETTER A WITH DIAERESIS'],
        ['229', 'LATIN SMALL LETTER A WITH RING ABOVE'],
        ['230', 'LATIN SMALL LETTER AE'],
        ['231', 'LATIN SMALL LETTER C WITH CEDILLA'],
        ['232', 'LATIN SMALL LETTER E WITH GRAVE'],
        ['233', 'LATIN SMALL LETTER E WITH ACUTE'],
        ['234', 'LATIN SMALL LETTER E WITH CIRCUMFLEX'],
        ['235', 'LATIN SMALL LETTER E WITH DIAERESIS'],
        ['236', 'LATIN SMALL LETTER I WITH GRAVE'],
        ['237', 'LATIN SMALL LETTER I WITH ACUTE'],
        ['238', 'LATIN SMALL LETTER I WITH CIRCUMFLEX'],
        ['239', 'LATIN SMALL LETTER I WITH DIAERESIS'],
        ['240', 'LATIN SMALL LETTER ETH'],
        ['241', 'LATIN SMALL LETTER N WITH TILDE'],
        ['242', 'LATIN SMALL LETTER O WITH GRAVE'],
        ['243', 'LATIN SMALL LETTER O WITH ACUTE'],
        ['244', 'LATIN SMALL LETTER O WITH CIRCUMFLEX'],
        ['245', 'LATIN SMALL LETTER O WITH TILDE'],
        ['246', 'LATIN SMALL LETTER O WITH DIAERESIS'],
        ['247', 'DIVISION SIGN'],
        ['248', 'LATIN SMALL LETTER O WITH STROKE'],
        ['249', 'LATIN SMALL LETTER U WITH GRAVE'],
        ['250', 'LATIN SMALL LETTER U WITH ACUTE'],
        ['251', 'LATIN SMALL LETTER U WITH CIRCUMFLEX'],
        ['252', 'LATIN SMALL LETTER U WITH DIAERESIS'],
        ['253', 'LATIN SMALL LETTER Y WITH ACUTE'],
        ['254', 'LATIN SMALL LETTER THORN'],
        ['255', 'LATIN SMALL LETTER Y WITH DIAERESIS'],
        ['338', 'LATIN SMALL LIGATURE OE'],
        ['339', 'LATIN SMALL LIGATURE OE'],
        ['372', 'LATIN CAPITAL LETTER W WITH CIRCUMFLEX'],
        ['374', 'LATIN CAPITAL LETTER Y WITH CIRCUMFLEX'],
        ['373', 'LATIN SMALL LETTER W WITH CIRCUMFLEX'],
        ['375', 'LATIN SMALL LETTER Y WITH CIRCUMFLEX'],
        ['8218', 'SINGLE LOW-9 QUOTATION MARK'],
        ['8219', 'single high-reversed-9 quotation mark'],
        ['8222', 'DOUBLE LOW-9 QUOTATION MARK'],
        ['8230', 'HORIZONTAL ELLIPSIS'],
        ['8482', 'TRADE MARK SIGN'],
        ['9658', 'BLACK RIGHT-POINTING POINTER'],
        ['8226', 'BULLET'],
        ['8594', 'RIGHTWARDS ARROW'],
        ['8658', 'RIGHTWARDS DOUBLE ARROW'],
        ['8660', 'LEFT RIGHT DOUBLE ARROW'],
        ['9830', 'BLACK DIAMOND SUIT'],
        ['8776', 'ALMOST EQUAL TO'],
        ['8656', 'LEFTWARDS DOUBLE ARROW'],
        ['8657', 'UPWARDS DOUBLE ARROW'],
        ['8659', 'DOWNWARDS DOUBLE ARROW'],
        ['8465', 'BLACK-LETTER CAPITAL I'],
        ['8476', 'BLACK-LETTER CAPITAL R'],
        ['8472', 'SCRIPT CAPITAL P'],
        ['9002', 'RIGHT-POINTING ANGLE BRACKET'],
        ['8992', 'TOP HALF INTEGRAL'],
        ['8993', 'BOTTOM HALF INTEGRAL'],
        ['177', 'PLUS-MINUS SIGN'],
        ['913', 'GREEK CAPITAL LETTER ALPHA'],
        ['914', 'GREEK CAPITAL LETTER BETA'],
        ['915', 'GREEK CAPITAL LETTER GAMMA'],
        ['916', 'GREEK CAPITAL LETTER DELTA'],
        ['917', 'GREEK CAPITAL LETTER EPSILON'],
        ['918', 'GREEK CAPITAL LETTER ZETA'],
        ['919', 'GREEK CAPITAL LETTER ETA'],
        ['920', 'GREEK CAPITAL LETTER THETA'],
        ['921', 'GREEK CAPITAL LETTER IOTA'],
        ['922', 'GREEK CAPITAL LETTER KAPPA'],
        ['923', 'GREEK CAPITAL LETTER LAMDA'],
        ['924', 'GREEK CAPITAL LETTER MU'],
        ['925', 'GREEK CAPITAL LETTER NU'],
        ['926', 'GREEK CAPITAL LETTER XI'],
        ['927', 'GREEK CAPITAL LETTER OMICRON'],
        ['928', 'GREEK CAPITAL LETTER PI'],
        ['929', 'GREEK CAPITAL LETTER RHO'],
        ['931', 'GREEK CAPITAL LETTER SIGMA'],
        ['932', 'GREEK CAPITAL LETTER TAU'],
        ['933', 'GREEK CAPITAL LETTER UPSILON'],
        ['934', 'GREEK CAPITAL LETTER PHI'],
        ['935', 'GREEK CAPITAL LETTER CHI'],
        ['936', 'GREEK CAPITAL LETTER PSI'],
        ['937', 'GREEK CAPITAL LETTER OMEGA'],
        ['945', 'GREEK SMALL LETTER ALPHA'],
        ['946', 'GREEK SMALL LETTER BETA'],
        ['947', 'GREEK SMALL LETTER GAMMA'],
        ['948', 'GREEK SMALL LETTER DELTA'],
        ['949', 'GREEK SMALL LETTER EPSILON'],
        ['950', 'GREEK SMALL LETTER ZETA'],
        ['951', 'GREEK SMALL LETTER ETA'],
        ['952', 'GREEK SMALL LETTER THETA'],
        ['953', 'GREEK SMALL LETTER IOTA'],
        ['954', 'GREEK SMALL LETTER KAPPA'],
        ['955', 'GREEK SMALL LETTER LAMDA'],
        ['956', 'GREEK SMALL LETTER MU'],
        ['957', 'GREEK SMALL LETTER NU'],
        ['958', 'GREEK SMALL LETTER XI'],
        ['959', 'GREEK SMALL LETTER OMICRON'],
        ['960', 'GREEK SMALL LETTER PI'],
        ['961', 'GREEK SMALL LETTER RHO'],
        ['963', 'GREEK SMALL LETTER SIGMA'],
        ['964', 'GREEK SMALL LETTER TAU'],
        ['965', 'GREEK SMALL LETTER UPSILON'],
        ['966', 'GREEK SMALL LETTER PHI'],
        ['967', 'GREEK SMALL LETTER CHI'],
        ['968', 'GREEK SMALL LETTER PSI'],
        ['969', 'GREEK SMALL LETTER OMEGA'],
        ['977', 'GREEK THETA SYMBOL'],
        ['981', 'GREEK PHI SYMBOL'],
        ['982', 'GREEK PI SYMBOL'],
        ['8707', 'THERE EXISTS'],
        ['8717', 'SMALL CONTAINS AS MEMBER'],
        ['8773', 'APPROXIMATELY EQUAL TO'],
        ['8756', 'THEREFORE'],
        ['8869', 'UP TACK'],
        ['8764', 'TILDE OPERATOR'],
        ['8804', 'LESS-THAN OR EQUAL TO'],
        ['8805', 'GREATER-THAN OR EQUAL TO'],
        ['8734', 'INFINITY'],
        ['8733', 'PROPORTIONAL TO'],
        ['8706', 'PARTIAL DIFFERENTIAL'],
        ['8729', 'BULLET OPERATOR'],
        ['8800', 'NOT EQUAL TO'],
        ['8801', 'IDENTICAL TO'],
        ['8776', 'ALMOST EQUAL TO'],
        ['8855', 'CIRCLED TIMES'],
        ['8853', 'CIRCLED PLUS'],
        ['8709', 'EMPTY SET'],
        ['8745', 'INTERSECTION'],
        ['8746', 'UNION'],
        ['8835', 'SUPERSET OF'],
        ['8839', 'SUPERSET OF OR EQUAL TO'],
        ['8836', 'NOT A SUBSET OF'],
        ['8834', 'SUBSET OF'],
        ['8838', 'SUBSET OF OR EQUAL TO'],
        ['8712', 'ELEMENT OF'],
        ['8713', 'NOT AN ELEMENT OF'],
        ['8736', 'ANGLE'],
        ['8711', 'NABLA'],
        ['8719', 'N-ARY PRODUCT'],
        ['8730', 'SQUARE ROOT'],
        ['8901', 'DOT OPERATOR'],
        ['8743', 'LOGICAL AND'],
        ['8744', 'LOGICAL OR'],
        ['8721', 'N-ARY SUMMATION'],
        ['8747', 'INTEGRAL'],
        ['978', 'GREEK UPSILON WITH HOOK SYMBOL'],
        ['8242', 'PRIME'],
        ['8243', 'DOUBLE PRIME'],
        ['176', 'DEGREE SIGN'],
        ['8230', 'HORIZONTAL ELLIPSIS'],
        ['8592', 'LEFTWARDS ARROW'],
        ['8593', 'UPWARDS ARROW'],
        ['8595', 'DOWNWARDS ARROW'],
        ['8629', 'DOWNWARDS ARROW WITH CORNER LEFTWARDS']
    ];
});
